### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by elyday** [bastinald/ui#7]
Hey,

i saw your video https://www.youtube.com/watch?v=CYl1pMgiecU and wrote a comment that i don't saw anymore so i write this issue for some questions.

First, i already used https://github.com/bastinald/laravel-livewire-auth and it works some perfect and i will take a look at this too.

But i have some questions before i will do this:
1. I had several problems when i wanted to inject some service containers via dependency injection at the mount function. Is this here also a problem? Have i to use `$this->emit('showModal', 'foo', $service)` or can i inject these service directly via the mount function?
2. Is there a way to save a migration log for the automatic migrations? I want to have some logs for these insteadof creating incremental migration files to have a sort of logging.
3. i had one more question but i forgot it :D

Greetings

**Comment by bastinald** [comment]
yeah i don't see the comment either but i got a notification for it. weird. 

1. with this package you should be able to use DI in the mount method. 
2. you can always use version control commit history for this. 

hope this helps

**Comment by elyday** [comment]
Yeah ok, i will try the di.

But for second: commit history is a way to do this but it is more for me to see when which migrations was executed and primary in which order. By the default migrations i have a way to order them via the date in the filename to resolve also dependencies between the migrations (for relations or some other stuff).

Now i remind my third question:
You announced at the beginning of the video that you will talk about why you archive all of your packages/repositories but you dont have talked about that. Will there be a video about this soon?

And are you planning to maintain this package for a longer time? And when yes do you provide upgrade instructions when major version will change in the future? Also is there some planning to setup a little documentation site next to the README?

**Comment by bastinald** [comment]
You can just use traditional migrations if you prefer. Just dont use the `ui:model` command, use the regular `make:model` command. You'll just have to look at the Laravel repository and put the `User` and `UserFactory` to their defaults. There is also a new `timezone` field you will have to add to your migrations as well.

I trimmed out the explanation as to why I archived the old repositories. The reason was because of trolls. I'm not going to be archiving this one. It will be actively maintained as I'm using it for all my projects going forward.

I can set up a documentation site, just need to make time.

**Comment by elyday** [comment]
Ok, thanks for the answer. I think i will use the regular migrations for my project.

Trolls are never really be fun. Trolls are sad designs. I am looking forward for the documentation site.

Thanks for your work!
